name: Check App
on:
  push:
  workflow_dispatch:

jobs:
  clean:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf build/
          xcodebuild clean

  build-ios:
    needs: clean
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26_beta_7.app || sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Build app
        working-directory: Inventaire
        run: |
          xcodebuild clean archive \
            -workspace project.xcworkspace \
            -scheme Inventaire \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/Inventaire.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Make ipa
        working-directory: InventaireApp
        run: |
            cd build/Inventaire.xcarchive/Products
            mv Applications Payload
            cd ../
            zip -r ../Inventaire.ipa Payload
            rm -rf Payload

      - name: Upload ipa
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: InventaireApp/build/Inventaire.ipa
          if-no-files-found: error